routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function ( ) {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('Materia', 'MateriaController');
    Route::resource('Alumno', 'AlumnoController');
    Route::resource('Kardex', 'KardexController');

    //Route::get('/', 'KardexController@index')->name('Kardex');
    Route::get('descargar', 'KardexController@pdf')->name('Kardex');
});

app/Kardex.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kardex extends Model
{
    //
    protected $table = 'kardex';
    protected $fillable = ['calificacion','idMateria'];
    protected $guarded = ['id'];



    public function Materias()
    {
        //return $this->belongsTo(materia::class,'idMateria');
        //return $this->belongsTo('App\Models\Materia','id','idMateria');
        return $this->belongsTo(Materia::class,'idMateria', 'id');
    }
    
    
}

app/Http/Controllers/KardexController.php
<?php

namespace App\Http\Controllers;
use App\Kardex;
use App\Materia;
use Illuminate\Http\Request;
use Barryvdh\DomPDF\Facade as PDF;

class KardexController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //Kardex::with('Materias')->orderBy('id','DESC')->paginate(3);
        $kardex = Kardex::select()->with('Materias')->orderBy('id','DESC')->paginate(3);
        return view('Kardex.index',compact('kardex'));
    }
    public function pdf()
    {        
        /**
         * toma en cuenta que para ver los mismos 
         * datos debemos hacer la misma consulta
        **/
        $kardex = Kardex::all(); 

        $pdf = PDF::loadView('pdf.kardex', compact('kardex'));

        return $pdf->download('listado.pdf');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $Materias =Materia::orderBy('id','DESC')->paginate(3);
        return view('Kardex.create',compact('Materias'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[ 'calificacion'=>'required', 
        'idMateria'=>'required']);
        Kardex::create($request->all());
        return redirect()->route('Kardex.index')->with('success','Registro creado satisfactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $kardexs=Kardex::find($id);
        return  view('Kardex.show',compact('kardexs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $Materias =Materia::orderBy('id','DESC')->paginate(3);
        $kardex=Kardex::find($id);
        return view('Kardex.edit',compact('kardex','Materias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[ 'calificacion'=>'required', 
        'idMateria'=>'required']);
 
        Kardex::find($id)->update($request->all());
        return redirect()->route('Kardex.index')->with('success','Registro actualizado satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Kardex::find($id)->delete();
        return redirect()->route('Kardex.index')->with('success','Registro eliminado satisfactoriamente');
    }
}

resources/views/Kardex/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nuevo Kardex</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Kardex.store') }}"  role="form">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="calificacion" id="calificacion" class="form-control input-sm" placeholder="Calificacion de la materia">
									</div>
                                    <div class="form-group">
									<select name="idMateria" id="idMateria">
											@foreach($Materias as $materia)
                                            
                                                <option  value="{{$materia->id}}">{{$materia->nombre}}</option>
                                            @endforeach
                                  </select>
									</div>
								</div>
								
							</div>

			
	
							<div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block">
									<a href="{{ route('Kardex.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	
                            </div>

                                

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/Kardex/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Editar Kardex</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Kardex.update',$kardex->id) }}"  role="form">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									
									<div class="form-group">
										<input type="text" name="calificacion" id="calificacion" class="form-control input-sm" value="{{$kardex->calificacion}}">
									</div>
                                    <div class="form-group">
									<select name="idMateria" id="idMateria" value="{{$kardex->idMateria}}">
											@foreach($Materias as $materia)
                                            
                                                <option  value="{{$materia->id}}">{{$materia->nombre}}</option>
                                            @endforeach
                                  	</select>
									</div>
								</div>
								
								
								
							</div>

								<div class="row">

								<div class="col-xs-6 col-sm-6 col-md-6">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block">
									<a href="{{ route('Kardex.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/Kardex/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <section class="content">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="pull-left"><h3>Lista Kardex</h3></div>
          <div class="pull-right">
            <div class="btn-group">
              <a href="{{ route('Kardex.create') }}" class="btn btn-info" >Añadir Kardex</a>
            </div>
          </div>
          <div class="table-container">
            <table id="mytable" class="table table-bordred table-striped">
             <thead>
               <th>Calificacion</th>
               <th>Materia</th>
               <th>Editar</th>
               <th>Eliminar</th>
               <th>PDF</th>
             </thead>
             <tbody>
              @if($kardex ->count())  
              @foreach($kardex  as $item)  
              <tr>
              @if($item->calificacion< 8)
              <td style="background-color: red;">{{$item->calificacion}}</td>
              @else
                <td>{{$item->calificacion}}</td>
              @endif
                <td>{{$item->Materias->nombre }}</td>
              
                <td><a class="btn btn-primary btn-xs" href="{{action('KardexController@edit', $item->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>
                  <form action="{{action('KardexController@destroy', $item->id)}}" method="post">
                   {{csrf_field()}}
                   <input name="_method" type="hidden" value="DELETE">

                   <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span></button>
                 </td>
                 <td>
                 <p>
                    <a href="{{ route('Kardex') }}" class="btn btn-sm btn-primary">
                        DescargarPDF
                    </a>
                </p>
                 </td>
               </tr>
               @endforeach 
              
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
             
            </tbody>
           
          </table>
        </div>
      </div>
      {{ $kardex->links() }}
    </div>
  </div>
</section>

@endsection