routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function ( ) {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('Materia', 'MateriaController');
    Route::resource('Alumno', 'AlumnoController');
    Route::resource('Kardex', 'KardexController');

    //Route::get('/', 'KardexController@index')->name('Kardex');
    Route::get('descargar', 'KardexController@pdf')->name('Kardex');
});

app/Alumno.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Alumno extends Model
{
    //
    protected $fillable = ['matricula', 'nombre', 'grado','carrera'];
}

app/Http/Controllers/AlumnoController.php
<?php

namespace App\Http\Controllers;
use App\Alumno;

use Illuminate\Http\Request;

class AlumnoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $alumnos=Alumno::orderBy('id','DESC')->paginate(3);
        return view('Alumno.index',compact('alumnos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Alumno.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[ 'matricula'=>'required', 
        'nombre'=>'required', 'grado'=>'required',
         'carrera'=>'required']);
        Alumno::create($request->all());
        return redirect()->route('Alumno.index')->with('success','Registro creado satisfactoriamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $alumnos=Alumno::find($id);
        return  view('Alumno.show',compact('alumnos'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $alumnos=Alumno::find($id);
        return view('Alumno.edit',compact('alumnos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[ 'matricula'=>'required', 
        'nombre'=>'required', 'grado'=>'required',
         'carrera'=>'required']);
 
        Alumno::find($id)->update($request->all());
        return redirect()->route('Alumno.index')->with('success','Registro actualizado satisfactoriamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Alumno::find($id)->delete();
        return redirect()->route('Alumno.index')->with('success','Registro eliminado satisfactoriamente');
    }
}

resources/views/Alumno/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nuevo Alumno</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Alumno.store') }}"  role="form">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="matricula" id="matricula" class="form-control input-sm" placeholder="Matricula del alumno">
									</div>
                                    <div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" placeholder="Nombre del alumno">
									</div>
                                    <div class="form-group">
										<input type="text" name="grado" id="grado" class="form-control input-sm" placeholder="Grado del alumno">
									</div>
                                    <div class="form-group">
										<input type="text" name="carrera" id="carrera" class="form-control input-sm" placeholder="Carrera del alumno">
									</div>
								</div>
								
							</div>

			
	
							<div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block">
									<a href="{{ route('Alumno.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	
                            </div>

                                

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/Alumno/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Editar Alumno</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Alumno.update',$alumnos->id) }}"  role="form">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="matricula" id="matricula" class="form-control input-sm" value="{{$alumnos->matricula}}">
									</div>
                                    <div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" value="{{$alumnos->nombre}}">
									</div>
                                   
									<div class="form-group">
										<input type="text" name="grado" id="grado" class="form-control input-sm" value="{{$alumnos->grado}}">
									</div>
                                    <div class="form-group">
										<input type="text" name="carrera" id="carrera" class="form-control input-sm" value="{{$alumnos->carrera}}">
									</div>
								
								</div>
								
							</div>

								<div class="row">

								<div class="col-xs-6 col-sm-6 col-md-6">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block">
									<a href="{{ route('Alumno.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/Alumno/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <section class="content">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="pull-left"><h3>Lista Alumnos</h3></div>
          <div class="pull-right">
            <div class="btn-group">
              <a href="{{ route('Alumno.create') }}" class="btn btn-info" >Añadir Alumno</a>
            </div>
          </div>
          <div class="table-container">
            <table id="mytable" class="table table-bordred table-striped">
             <thead>
               <th>Matricula</th>
               <th>Nombre</th>
               <th>Grado</th>
               <th>Carrera</th>
               <th>Editar</th>
               <th>Eliminar</th>
             </thead>
             <tbody>
              @if($alumnos->count())  
              @foreach($alumnos as $alumno)  
              <tr>
                <td>{{$alumno->matricula}}</td>
                <td>{{$alumno->nombre}}</td>
                <td>{{$alumno->grado}}</td>
                <td>{{$alumno->carrera}}</td>
                <td><a class="btn btn-primary btn-xs" href="{{action('AlumnoController@edit', $alumno->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>
                  <form action="{{action('AlumnoController@destroy', $alumno->id)}}" method="post">
                   {{csrf_field()}}
                   <input name="_method" type="hidden" value="DELETE">

                   <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span></button>
                 </td>
               </tr>
               @endforeach   
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
            </tbody>

          </table>
        </div>
      </div>
      {{ $alumnos->links() }}
    </div>
  </div>
</section>

@endsection