routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::middleware('auth')->group(function ( ) {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('Materia', 'MateriaController');
    Route::resource('Alumno', 'AlumnoController');
    Route::resource('Kardex', 'KardexController');

    //Route::get('/', 'KardexController@index')->name('Kardex');
    Route::get('descargar', 'KardexController@pdf')->name('Kardex');
});

app/Materia.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Materia extends Model
{
    //
    protected $fillable = ['nombre', 'codigo', 'grado','cal_min'];

}

app/Http/Controllers/MateriaController.php
<?php

namespace App\Http\Controllers;
use App\Materia;

use Illuminate\Http\Request;

class MateriaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $materias=Materia::orderBy('id','DESC')->paginate(3);
        return view('Materia.index',compact('materias')); 
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Materia.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request,[ 'nombre'=>'required', 
        'codigo'=>'required', 'grado'=>'required',
         'cal_min'=>'required']);
        Materia::create($request->all());
        return redirect()->route('Materia.index')->with('success','Registro creado satisfactoriamente');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $materias=Materia::find($id);
        return  view('Materia.show',compact('materias'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $materias=Materia::find($id);
        return view('Materia.edit',compact('materias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request,[ 'nombre'=>'required', 
        'codigo'=>'required', 'grado'=>'required',
         'cal_min'=>'required']);
 
        Materia::find($id)->update($request->all());
        return redirect()->route('Materia.index')->with('success','Registro actualizado satisfactoriamente');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        Materia::find($id)->delete();
        return redirect()->route('Materia.index')->with('success','Registro eliminado satisfactoriamente');
    
    }
}

resources/views/Materia/create.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Nueva Materia</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Materia.store') }}"  role="form">
							{{ csrf_field() }}
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" placeholder="Nombre de la materia">
									</div>
                                    <div class="form-group">
										<input type="text" name="codigo" id="codigo" class="form-control input-sm" placeholder="codigo de la materia">
									</div>
                                    <div class="form-group">
										<input type="text" name="grado" id="grado" class="form-control input-sm" placeholder="grado de la materia">
									</div>
                                    <div class="form-group">
										<input type="number" name="cal_min" id="cal_min" class="form-control input-sm" placeholder="calificacion minima de la materia">
									</div>
								</div>
								
							</div>

			
	
							<div class="row">
                            <div class="col-xs-6 col-sm-6 col-md-6">
									<input type="submit"  value="Guardar" class="btn btn-success btn-block">
									<a href="{{ route('Materia.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	
                            </div>

                                

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/Materia/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
	<section class="content">
		<div class="col-md-8 col-md-offset-2">
			@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Error!</strong> Revise los campos obligatorios.<br><br>
				<ul>
					@foreach ($errors->all() as $error)
					<li>{{ $error }}</li>
					@endforeach
				</ul>
			</div>
			@endif
			@if(Session::has('success'))
			<div class="alert alert-info">
				{{Session::get('success')}}
			</div>
			@endif

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Editar Materia</h3>
				</div>
				<div class="panel-body">					
					<div class="table-container">
						<form method="POST" action="{{ route('Materia.update',$materias->id) }}"  role="form">
							{{ csrf_field() }}
							<input name="_method" type="hidden" value="PATCH">
							<div class="row">
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div class="form-group">
										<input type="text" name="nombre" id="nombre" class="form-control input-sm" value="{{$materias->nombre}}">
									</div>
                                    <div class="form-group">
										<input type="text" name="codigo" id="codigo" class="form-control input-sm" value="{{$materias->codigo}}">
									</div>
                                   
									<div class="form-group">
										<input type="text" name="grado" id="grado" class="form-control input-sm" value="{{$materias->grado}}">
									</div>
                                    <div class="form-group">
										<input type="number" name="cal_min" id="cal_min" class="form-control input-sm" value="{{$materias->cal_min}}">
									</div>
								
								</div>
								
							</div>

								<div class="row">

								<div class="col-xs-6 col-sm-6 col-md-6">
									<input type="submit"  value="Actualizar" class="btn btn-success btn-block">
									<a href="{{ route('Materia.index') }}" class="btn btn-info btn-block" >Atrás</a>
								</div>	

							</div>
						</form>
					</div>
				</div>

			</div>
		</div>
	</section>
	@endsection

resources/views/Materia/index.blade.php
@extends('layouts.app')
@section('content')
<div class="row">
  <section class="content">
    <div class="col-md-8 col-md-offset-2">
      <div class="panel panel-default">
        <div class="panel-body">
          <div class="pull-left"><h3>Lista Materias</h3></div>
          <div class="pull-right">
            <div class="btn-group">
              <a href="{{ route('Materia.create') }}" class="btn btn-info" >Añadir Materia</a>
            </div>
          </div>
          <div class="table-container">
            <table id="mytable" class="table table-bordred table-striped">
             <thead>
               <th>Nombre</th>
               <th>codigo</th>
               <th>Grado</th>
               <th>calificacion</th>
               <th>Editar</th>
               <th>Eliminar</th>
             </thead>
             <tbody>
              @if($materias->count())  
              @foreach($materias as $materia)  
              <tr>
                <td>{{$materia->nombre}}</td>
                <td>{{$materia->codigo}}</td>
                <td>{{$materia->grado}}</td>
                <td>{{$materia->cal_min}}</td>
                <td><a class="btn btn-primary btn-xs" href="{{action('MateriaController@edit', $materia->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a></td>
                <td>
                  <form action="{{action('MateriaController@destroy', $materia->id)}}" method="post">
                   {{csrf_field()}}
                   <input name="_method" type="hidden" value="DELETE">

                   <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span></button>
                 </td>
               </tr>
               @endforeach   
               @else
               <tr>
                <td colspan="8">No hay registro !!</td>
              </tr>
              @endif
            </tbody>

          </table>
        </div>
      </div>
      {{ $materias->links() }}
    </div>
  </div>
</section>

@endsection